### ISSUE TITLE
Unclear error message when TeamCity project name has changed

### ISSUE THREAD

**Issue by rmunn** [ermshiperete/BuildDependency#19]
If a TeamCity project name has changed (e.g., from `...Trusty64...` to `...Linux64...`), the current error message that will be displayed is:

```text
Can't interpret line 9. Skipping [TC::ChorusTrusty64lfmergeCont].
```

It would be better if that error message said something like "Can't find project named `ChorusTrusty64lfmergeCont` in line 9 of (filename).dep".

**Comment by ermshiperete** [comment]
Fixed in v0.2.11
